/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package br.ufpe.cin.gradle.tutorial;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class AppTest {
    @Test void appHasAGreeting() {
        App classUnderTest = new App();
        assertNotNull(classUnderTest.getGreeting(), "app should have a greeting");
    }

    @Test void appSaysHelloWorld() {
        App classUnderTest = new App();
        assertEquals("Olá, mundo!", classUnderTest.getGreeting(), "A função deveria retornar a string 'Olá, mundo!'");
    }
}
